import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ContactFloating from "@/components/ContactFloating";
import { Parkinsans, DM_Sans } from "next/font/google";

const parkinsans = Parkinsans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-parkinsans",
});

const dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${parkinsans.variable} ${dm_sans.variable} font-sans`}>
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <div className="flex-1">{children}</div>
          <Footer />
          <ContactFloating />
        </div>
      </body>
    </html>
  );
}
